# Instruction:
# * Ensure you have the following R libraries installed via the following:
#   `devtools::install_github("rstudio/reticulate"); install.packages(c("stringr", "roxygen2))`
# * Change variable `pkg_location` below to point to your R package directory
# * Run `use_condaenv()`, `use_python()`, or `use_virtualenv()` from reticulate to activate the
#   environment with tensorflow-io installed. 
#   e.g. use_condaenv("tensorflow-io", conda = "~/miniconda3/envs/py36/bin/conda")
#   Note that you should insert this line right after loading reticulate package.
library(reticulate)
library(stringr)
library(roxygen2)
pkg_location <- "~/repos/io/R-package"


# Note: Code below should not be changed unless necessary
setwd(pkg_location)
tfio_lib <- import("tensorflow_io")

source(paste0(pkg_location, "scripts/gen_wrapper_utils.R"))

generated_wrappers_file_name <- "R/auto_generated_wrappers.R"
write(paste0(
  "# -------------------------------------------------------------------------------
#             *** WARNING: DO NOT MODIFY THIS FILE ***
#              
# Instead, modify scripts/gen_wrappers.R which automatically generates this file.\n#\n",
  "# Generated by reticulate v", packageVersion("reticulate"),
  "\n# ------------------------------------------------------------------------------- \n"
), file = generated_wrappers_file_name)

py_function_custom_scaffold(
  "tfio_lib$kafka$KafkaDataset",
  r_function = "kafka_dataset",
  process_param_fn = process_int_param_fn,
  postprocess_fn = function() { "as_tf_dataset(python_function_result)" },
  file_name = generated_wrappers_file_name)

# Regenerate NAMESPACE and .Rd files
roxygen2::roxygenise(pkg_location)
