# Copyright 2023 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Generator"""

import abc
import hashlib
import tensorflow as tf

from tests.test_atds_avro.utils.hash_util import int_to_bytes


class Generator(metaclass=abc.ABCMeta):
    """Base class for tensor generator.

    Generator generates tf.Tensor, tf.sparse.SparseTensor, or
    tf.RaggedTensor based on the input spec. The spec is one of the
    tf.TensorSpec, tf.SparseTensorSpec or tf.RaggedTensorSpec.
    """

    _SUPPORTED_SPEC = (tf.TensorSpec, tf.SparseTensorSpec, tf.RaggedTensorSpec)

    # The value used in hashing None dimension.
    _NONE_HASH_VALUE = "None"
    _SHAPE_HASH_VALUE = "shape"
    _DTYPE_HASH_VALUE = "dtype"

    def __init__(self, spec):
        """Create a new Generator.

        This must be called by the constructors of subclasses.

        Args:
          spec: A tf.TensorSpec, tf.SparseTensorSpec or tf.RaggedTensorSpec that
            describes the tensor generated by this generator.

        Raises:
          TypeError: If spec is not one of the tf.TensorSpec, tf.SparseTensorSpec
            or tf.RaggedTensorSpec.
        """
        if not isinstance(spec, Generator._SUPPORTED_SPEC):
            raise TypeError(
                "Generator can only accept spec in one of the "
                f"{Generator._SUPPORTED_SPEC} types but found {spec}."
            )
        self._spec = spec

    @property
    def spec(self):
        """Return the spec that the generator will follow.

        The spec is one of the tf.TensorSpec, tf.SparseTensorSpec, and
        tf.RaggedTensorSpec.
        """
        return self._spec

    @abc.abstractmethod
    def generate(self):
        """Generate tensor value based on the spec of the generator.

        The output tensor must be compatible with the spec.

        When the spec is tf.TensorSpec, tf.SparseTensorSpec, or
        tf.RaggedTensorSpec, this function will return tf.Tensor,
        tf.sparse.SparseTensor, or tf.RaggedTensor respectively.

        Returns:
          tf.Tensor, tf.sparse.SparseTensor, or tf.RaggedTensor

        Raises:
          NotImplementedError: If subclass does not overload the function.
        """
        raise NotImplementedError

    def get_generator_cls(self):
        """Get the generator class which this object represents."""
        return type(self)

    def hash_code(self):
        """Return the hasehd code of this Generator in hex str.

        The hashed code helps create the data source cache path on disk.

        Returns:
          A hashed hex str of this Generator.
        """
        m = hashlib.sha256()

        # Step 1: hash class name
        classname = self.get_generator_cls().__name__
        m.update(classname.encode())

        # Step 2: hash input spec using default hash function in tf.TypeSpec
        if isinstance(self.spec, tf.TensorSpec):
            m.update(tf.TensorSpec.__name__.encode())
        elif isinstance(self.spec, tf.SparseTensorSpec):
            m.update(tf.SparseTensorSpec.__name__.encode())
        elif isinstance(self.spec, tf.RaggedTensorSpec):
            m.update(tf.RaggedTensorSpec.__name__.encode())
            m.update(b"ragged_rank")
            m.update(int_to_bytes(self.spec.ragged_rank))
            m.update(b"row_splits_dtype")
            m.update(int_to_bytes(hash(self.spec.row_splits_dtype)))
            m.update(b"flat_values_spec")
            if self.spec.flat_values_spec:
                m.update(int_to_bytes(hash(self.spec.flat_values_spec)))
        else:
            raise TypeError(
                f"Generator.spec is not one of {Generator._SUPPORTED_SPEC}."
            )

        self._hash_shape(m, self.spec.shape)
        self._hash_dtype(m, self.spec.dtype)

        # Step 3" return hashed hex str.
        return m.hexdigest()

    def _hash_shape(self, m, shape):
        """Hash shape info with a hash algorithm in hashlib.

        Args:
          m: A hashlib algorithm e.g. hashlib.sha256().
          shape: A list of python int.
        """
        m.update(Generator._SHAPE_HASH_VALUE.encode())
        for dim in shape:
            if dim is None:
                m.update(Generator._NONE_HASH_VALUE.encode())
            else:
                m.update(int_to_bytes(dim))

    def _hash_dtype(self, m, dtype):
        """Hash TensorFlow dtype with a hash algorithm in hashlib.

        Args:
          m: A hashlib algorithm e.g. hashlib.sha256().
          dtype: TensorFlow dtype e.g. tf.float32.
        """
        m.update(Generator._DTYPE_HASH_VALUE.encode())
        m.update(int_to_bytes(hash(dtype)))
