FROM centos:7

RUN yum install -y \
    git \
    gcc \
    patch \
    gcc-c++ \
    which \
    unzip

RUN yum clean all

# Version 0.10.0 build uses bazel 0.29.0
ARG BAZEL_VERSION=0.29.0
ARG BAZEL_OS=linux
RUN curl -OL https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${BAZEL_OS}-x86_64.sh && \
    bash -x bazel-${BAZEL_VERSION}-installer-${BAZEL_OS}-x86_64.sh && \
    rm bazel-${BAZEL_VERSION}-installer-${BAZEL_OS}-x86_64.sh

# Added miniconda due to lib path problems when working with python3 install
# Problem tensorflow installs headers in lib but the build chain here sets them up to be in lib64
ARG CONDA_OS=Linux

# Miniconda - Python 3.6, 64-bit, x86, latest
RUN curl -sL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o mconda-install.sh && \
    bash -x mconda-install.sh -b -p miniconda && \
    rm mconda-install.sh

ENV PATH="/miniconda/bin:$PATH"

ARG CONDA_ADD_PACKAGES=""

RUN conda create -y -q -n tfio-dev python=3.6 ${CONDA_ADD_PACKAGES}

ADD . /tensorflow-io
RUN cd /tensorflow-io && ./configure.sh
RUN cd /tensorflow-io && bazel build -s --verbose_failures //tensorflow_io/core/...

# Package and publish into the `dist` folder
RUN cd /tensorflow-io && python setup.py --data bazel-bin sdist