name: Release Note

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release-note:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
      - run: git tag
      - run: python3 tools/release/note_create.py
      - run: git diff
      - run: python3 tools/release/note_update.py
      - run: git diff
      - uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          commit-message: Update RELEASE.md [bot]
          branch: bot-RELEASE.md
          delete-branch: true
          title: 'Update RELEASE.md [bot]'
          body: |
            README.md: auto-updated by .github/workflows/release.note.yml
