name: Mark stale issues and pull requests

on:
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-18.04
    strategy:
      matrix:
      node_version: {'8', '10', '12']
      os: [ubuntu-latest, windows-latest, macOS-latest]
      
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
